### ISSUE TITLE
text infilling cases

### ISSUE THREAD

**Issue by qtli** [THUDM/GLM#30]
Thanks for your wonderful work!

I tried
```
bash scripts/generate_block.sh \
     config_tasks/model_blocklm_large.sh
```
with many context inputs, but got unsatisfied predictions (weird tokens or not consistently with local context), for example:
```
#1
Context: Ng is a good teacher at [MASK] .

GLM: [CLS] ng is a good teacher at [MASK] . [PAD] <|startofpiece|> are . e

#2
Context: Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a [MASK] in online education

GLM: [CLS] ng is an adjunct professor at [MASK] ( formerly associate professor and director of its stanford ai lab or sail ) . also a [MASK] in online education [PAD] <|startofpiece|> the university of arizona <|startofpiece|> researcher at the

#3
Context: Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a [MASK] in online education, Ng co-founded Coursera and deeplearning.ai.

GLM: [CLS] ng is an adjunct professor at [MASK] ( formerly associate professor and director of its stanford ai lab or sail ) . also a [MASK] in online education , ng co - founded coursera and deeplearning . ai . [PAD] <|startofpiece|> the university of michigan <|startofpiece|> senior associate at the university of
```

I want to generate multiple spans for a given context, I was wondering whether I have mistakes in using the scripts.

**Comment by Xiao9905** [comment]
@qtli Hi,

Thanks for your interest in our work. I think there are two reasons accounted for this:

1. `Model scale`: the default model in your command is `model_blocklm_large.sh`, which is a model with only 335M parameters. Models at this scale should not be expected to generate consistent and very satisfying output without proper fine-tuning. Please try larger models like `model_blocklm_1.5_generation.sh` (515M), `model_blocklm_2B.sh` (2B), or `model_blocklm_10B.sh` (10B).
2. `Default decoding strategy`: the default strategy in the script you have run is based on top-k sampling, which is a random decoding strategy. In most cases, this strategy does not output the best scored output. You may try beam search (as stated in an [example scripts of GLM-130B](https://github.com/THUDM/GLM-130B/blob/main/scripts/generate.sh)) for better and more consistent generation.

I hope my answers can help you. Feel free ask other questions if you need help.

**Comment by qtli** [comment]
Thanks for your prompt reply!

I have downloaded 2B model and change the generate_block.sh into:
```
#!/bin/bash
CHECKPOINT_PATH=/root/data/checkpoints

source $1

MPSIZE=1
MAXSEQLEN=512
MASTER_PORT=$(shuf -n 1 -i 10000-65535)

# BeamSearchStrategy args
NUM_BEAMS=4
LENGTH_PENALTY=1.0
NO_REPEAT_NGRAM=3

#SAMPLING ARGS
TEMP=0.9
#If TOPK/TOPP are 0 it defaults to greedy sampling, top-k will also override top-p
#TOPK=40
TOPK=1
TOPP=0

script_path=$(realpath $0)
script_dir=$(dirname $script_path)

config_json="$script_dir/ds_config.json"

python -m torch.distributed.launch --nproc_per_node=$MPSIZE --master_port $MASTER_PORT generate_samples.py \
       --DDP-impl none \
       --model-parallel-size $MPSIZE \
       $MODEL_ARGS \
       --fp16 \
       --cache-dir cache \
       --out-seq-length $MAXSEQLEN \
       --seq-length 512 \
       --num-beams $NUM_BEAMS \
       --length-penalty $LENGTH_PENALTY \
       --no-repeat-ngram-size $NO_REPEAT_NGRAM \
       --temperature $TEMP \
       --top_k $TOPK \
       --top_p $TOPP
```
and run:
```
bash scripts/generate_block.sh config_tasks/model_blocklm_2B.sh
```
However, it reports bug, like:
```
Context prompt (stop to exit) >>> Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.
Traceback (most recent call last):
  File "generate_samples.py", line 348, in <module>
    main()
  File "generate_samples.py", line 344, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 299, in generate_samples
    tokens, mems = sample_sequence(model, tokenizer, tokens, position,
  File "generate_samples.py", line 207, in sample_sequence
    tokens, mems = beam_scorer.finalize(tokens, beam_scores, next_tokens, next_indices, eos_token_id=args.eod_token,
  File "/GLM/generation_utils.py", line 308, in finalize
    decoded[i, : sent_lengths[i]] = hypo
RuntimeError: The expanded size of the tensor (512) must match the existing size (513) at non-singleton dimension 0.  Target sizes: [512].  Tensor sizes: [513]
Traceback (most recent call last):
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/glm/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '36', '--hidden-size', '2048', '--num-attention-heads', '32', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--load-pretrained', '/GLM/blocklm-2b/blocklm-2b-512', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--num-beams', '4', '--length-penalty', '1.0', '--no-repeat-ngram-size', '3', '--temperature', '0.9', '--top_k', '1', '--top_p', '0']' returned non-zero exit status 1.
```

Could you give me some hints about this bug? Thanks in advance.

**Comment by duzx16** [comment]
Can you provide the prompt that causes the error?

**Comment by Xiao9905** [comment]
> --seq-length 512 \

@qtli Hi,

I think changing this to 513 will solve the problem. Maybe you can have a try.

**Comment by duzx16** [comment]
> > Can you provide the prompt that causes the error?
> 
> @duzx16 hi, the prompt is `Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.`
> 
> > > --seq-length 512 \
> > 
> > 
> > @qtli Hi,
> > I think changing this to 513 will solve the problem. Maybe you can have a try.
> 
> @Xiao9905 Hi, i try change it but it fails. I find the line 296 in generation_utils.py have some relation with the length bug:
> 
> ```
> sent_max_len = min(sent_lengths.max().item(), self.max_length)
> ```
> 
> But if I change min to max, it reports a new bug:
> 
> ```
> Context prompt (stop to exit) >>> Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.
> > /GLM/generation_utils.py(309)finalize()
> -> decoded[i, : sent_lengths[i]] = hypo
> (Pdb) c
> Traceback (most recent call last):
>   File "generate_samples.py", line 348, in <module>
>     main()
>   File "generate_samples.py", line 344, in main
>     generate_samples(model, tokenizer, args, torch.cuda.current_device())
>   File "generate_samples.py", line 299, in generate_samples
>     tokens, mems = sample_sequence(model, tokenizer, tokens, position,
>   File "generate_samples.py", line 207, in sample_sequence
>     tokens, mems = beam_scorer.finalize(tokens, beam_scores, next_tokens, next_indices, eos_token_id=args.eod_token,
> ValueError: too many values to unpack (expected 2)
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
>     main()
>   File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
>     raise subprocess.CalledProcessError(returncode=process.returncode,
> subprocess.CalledProcessError: Command '['/root/anaconda3/envs/glm/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '36', '--hidden-size', '2048', '--num-attention-heads', '32', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--load-pretrained', '/GLM/blocklm-2b/blocklm-2b-512', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--num-beams', '4', '--length-penalty', '1.0', '--no-repeat-ngram-size', '3', '--temperature', '0.9', '--top_k', '1', '--top_p', '0']' returned non-zero exit status 1
> ```

@qtli This bug has been fixed. Can you pull the latest code and retry?

**Comment by qtli** [comment]
@duzx16 Many thanks for your help. I pull the updated code and test again. It shows a warning (we need a latest_checkpointed_iteration.txt in blocklm-2b-512/) and I don't know if I could ignore it.
```
->0->-1/-1/-1 [22] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [23] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [24] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [25] -1/-1/-1->0->-1|-1->0->-1/-1
ts-03fcc044fa9e464396bb976d1b07fb38-launcher:1004:1024 [0] NCCL INFO Setting affinity for GPU 0 to ff,ffff0000,00fffffc
ts-03fcc044fa9e464396bb976d1b07fb38-launcher:1004:1024 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
ts-03fcc044fa9e464396bb976d1b07fb38-launcher:1004:1024 [0] NCCL INFO comm 0x7f91c4000e50 rank 0 nranks 1 cudaDev 0 busId 1a000 - Init COMPLETE
building GPT2 model ...
 > number of parameters on model parallel rank 0: 1920122880
WARNING: could not find the metadata file /root/data/checkpoints/blocklm-2b-512/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random

Context prompt (stop to exit) >>> Prompt should not be empty!

Context prompt (stop to exit) >>> Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.
```

I still cannot use GLM_2B to generate spans via beam search. I do not whether I misuse the code. The error message is:
```
Context: Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.
Traceback (most recent call last):
  File "generate_samples.py", line 348, in <module>
    main()
  File "generate_samples.py", line 344, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 308, in generate_samples
    decode_tokens = tokenizer.DecodeIds(output_tokens_list.tolist())
  File "/GLM/data_utils/tokenization.py", line 1124, in DecodeIds
    return self.text_tokenizer.decode(Ids)
  File "/GLM/data_utils/tokenization_gpt2.py", line 273, in decode
    text = ''.join([self.decoder[token] for token in tokens])
  File "/GLM/data_utils/tokenization_gpt2.py", line 273, in <listcomp>
    text = ''.join([self.decoder[token] for token in tokens])
KeyError: 50287
Traceback (most recent call last):
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/glm/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '36', '--hidden-size', '2048', '--num-attention-heads', '32', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--load-pretrained', '/root/data/checkpoints/blocklm-2b-512', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--num-beams', '4', '--length-penalty', '1.0', '--no-repeat-ngram-size', '3', '--temperature', '0.9', '--top_k', '1', '--top_p', '0']' returned non-zero exit status 1.
```

Looking forward to your reply :)

**Comment by duzx16** [comment]
@qtli You should unzip the downloaded checkpoint into `/root/data/checkpoints/blocklm-2b-512`. In other words there should be a `mp_rank_00_model_states.pt` under `/root/data/checkpoints/blocklm-2b-512`. The default folder name after unzipping is `blocklm-2b` instead of `blocklm-2b-512`. I will fix that.

**Comment by qtli** [comment]
Hi, I fix the checkpoint path in the code but it still not works:
```
Context: Ng is an adjunct professor at [MASK] (formerly associate professor and Director of its Stanford AI Lab or SAIL ). Also a pioneer in online education, Ng co-founded Coursera and deeplearning.ai.
Traceback (most recent call last):
  File "generate_samples.py", line 348, in <module>
    main()
  File "generate_samples.py", line 344, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 308, in generate_samples
    decode_tokens = tokenizer.DecodeIds(output_tokens_list.tolist())
  File "/apdcephfs/share_916081/qintongli/Explanation_proj/GLM/data_utils/tokenization.py", line 1124, in DecodeIds
    return self.text_tokenizer.decode(Ids)
  File "/apdcephfs/share_916081/qintongli/Explanation_proj/GLM/data_utils/tokenization_gpt2.py", line 273, in decode
    text = ''.join([self.decoder[token] for token in tokens])
  File "/apdcephfs/share_916081/qintongli/Explanation_proj/GLM/data_utils/tokenization_gpt2.py", line 273, in <listcomp>
    text = ''.join([self.decoder[token] for token in tokens])
KeyError: 4633767520117668420
Traceback (most recent call last):
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/glm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/anaconda3/envs/glm/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/glm/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '36', '--hidden-size', '2048', '--num-attention-heads', '32', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--load-pretrained', '/apdcephfs/share_916081/qintongli/Explanation_proj/GLM//blocklm-2b', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--num-beams', '4', '--length-penalty', '1.0', '--no-repeat-ngram-size', '3', '--temperature', '0.9', '--top_k', '1', '--top_p', '0']' returned non-zero exit status 1.
```

**Comment by duzx16** [comment]
@qtli The error is caused by changing `min` to `max` in the line 296 in generation_utils.py. Can you please retry with the latest code?
Also, make sure you see `successfully loaded /root/data/checkpoints/blocklm-2b-512/mp_rank_00_model_states.pt` in the log.

**Comment by qtli** [comment]
Thanks for your reply. It works now!
